# Config file for automatic testing at travis-ci.org
language: python
sudo: false # use the new faster dockerized containers on Travis CI

matrix:
    include:
    # A the moment PY2.6 fails due to the use of dictionary comprehension
    # not sure if we want to support it
    #- python: "2.6"
    #  env: DEPS="numpy==1.8 nose"
    - python: "2.7"
      env: DEPS="numpy==1.9 nose"
    - python: "3.3"
      env: DEPS="numpy==1.9 nose"
    - python: "3.4"
      env: DEPS="numpy==1.11 nose"
    - python: "3.5"
      env: DEPS="numpy==1.11 nose"


before_install:
    - pip install setuptools --upgrade
    - pip install pip --upgrade
    - pip install $DEPS

script:
    - python setup.py egg_info
    - python setup.py nosetests -sv
    # Generate documentation
    #- cd doc
    #- make html
