# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"

env:
    - NUMPY=false PYTHON=python PYSUF='' # uses Python 2.7
    - NUMPY=true  PYTHON=python PYSUF='' # uses Python 2.7
    - NUMPY=false PYTHON=python3 PYSUF=3 # uses Python 3.2
    - NUMPY=true PYTHON=python3 PYSUF=3 # uses Python 3.2

# command to install dependencies
install:
  # Deactivate the virtualenv to get fast install of dependencies
  - deactivate
  - sudo apt-get install -qq $PYTHON-sphinx $PYTHON-nose
  - if $NUMPY; then sudo apt-get install -qq $PYTHON-numpy; fi
  - sudo python setup.py install

# command to run tests
script:
  # Run unit tests
  - nosetests$PYSUF
  # Generate documentation
  - cd doc
  - make html
 