# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.5"
  # !!!!! All version to be put back later
  # - "2.6"
  # - "2.7"
  # - "3.1"
  # - "3.2"

env:
    - NUMPY=true
    # - NUMPY=false  #!!!!!! to be put back later

    # - NUMPY=false PYTHON=python3 PYSUF=3 # uses Python 3.2
    # - NUMPY=true PYTHON=python3 PYSUF=3 # uses Python 3.2

# command to install dependencies
install:
  # Deactivate the virtualenv to get fast install of dependencies
  # - deactivate  #!!! commenting this out because it seems to replace Python by a different version

  # !!! A package that contains pdflatex is needed for the Sphinx
  # !!! document generation.
  - sudo apt-get install -qq python-sphinx python-nose 
  - if $NUMPY; then sudo apt-get install -qq python-numpy; fi
  - python --version

# command to run tests
script:
  # Run unit tests

  # Trying to get information on which nosetests is run:
  - cat =nosetests
  - python --version
  # Runs nosetests through the right Python interpreter
  - nosetests -sv
  # Generate documentation
  - cd doc
  - make html
 