# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"

# command to install dependencies
install:
  - time pip install --use-mirrors numpy sphinx

# command to run tests
script:
  # Run unit tests
  - nosetests
  # Generate documentation
  - cd doc
  - make html