# Config file for automatic testing at travis-ci.org

language: python

python:
  # !!!!! All version to be put back later
  # - "2.5"
  # - "2.6"
  # - "2.7"
  # - "3.1"
  - "3.2"

env:
    - NUMPY=true
    # - NUMPY=false  #!!!!!! to be put back later

    # - NUMPY=false PYTHON=python3 PYSUF=3 # uses Python 3.2
    # - NUMPY=true PYTHON=python3 PYSUF=3 # uses Python 3.2

# command to install dependencies
install:
  # !!! A package that contains pdflatex is needed for the Sphinx
  # !!! document generation.
  
  # - deactivate: not used, because it replaces the version of Python
  # - selected by the "python:" entry.

  # The Sphinx document requires pdflatex. It can be found in
  # textlive-latex-base; however this leads to an error (ecrm10...).
  - sudo apt-get install -qq python-sphinx python-nose texlive-full
  - if $NUMPY; then sudo apt-get install -qq python-numpy; fi
  - python --version

# command to run tests
script:

  # In order for the Python 3 version to be installed if needed, we
  # rely on the setup.py script:

  # nosetests uncertainties does not find the module, with a local
  # install:
  #- python setup.py install --user
  
  pip install --upgrade uncertainties

  # Run unit tests
  - python --version  # Additional check: did the install change anything?

  # Nosetests can automatically run the tests from the *installed
  # package*, but we must move away from the local uncertainties
  # module:
  - cd /tmp
  - nosetests -sv uncertainties
  # Generate documentation
  - cd doc
  - make html
 