# Config file for automatic testing at travis-ci.org

language: python

python:
  - "2.5"
  - "2.6"
  - "2.7"
  - "3.1"
  - "3.2"

env:
    - NUMPY=true
    - NUMPY=false
    # - NUMPY=false PYTHON=python3 PYSUF=3 # uses Python 3.2
    # - NUMPY=true PYTHON=python3 PYSUF=3 # uses Python 3.2

# command to install dependencies
install:
  # Deactivate the virtualenv to get fast install of dependencies
  - deactivate
  # texlive-base is for pdflatex, which is run by the Sphinx Makefile:
  - sudo apt-get install -qq python-sphinx python-nose texlive-base
  - if $NUMPY; then sudo apt-get install -qq python-numpy; fi
  - python setup.py install --user

# command to run tests
script:
  # Run unit tests
  - nosetests
  # Generate documentation
  - cd doc
  - make html
 