# Config file for automatic testing at travis-ci.org
language: python
sudo: false # use the new faster dockerized containers on Travis CI

matrix:
    include:
    - python: "2.7"
      env: DEPS="numpy nose"
    - python: "3.3"
      env: DEPS="numpy nose"
    - python: "3.4"
      env: DEPS="numpy nose"
    - python: "3.5"
      env: DEPS="numpy nose"
    - python: "3.6"
      env: DEPS="numpy nose"


before_install:
    - pip install setuptools --upgrade
    - pip install pip --upgrade
    - pip install $DEPS
    - pip install codecov

script:
    - python setup.py egg_info
    - python setup.py nosetests -sv --with-coverage
    - codecov
    # Generate documentation
    #- cd doc
    #- make html
